title:              花音的日常部落格
email:              kanon-blog@outlook.com
description:        內容主要圍繞動漫以及網上潮流
author:             花音
baseurl:            "/kanon-blog"
url:                "https://kanonblog.github.io/"

# Social Profiles
twitter_username:   
github_username: kanonblog
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
